// HomePage.js
import React, { useState } from 'react';
import "./HomePage.css";
import IconButton from "../IconButton/IconButton";
import CardList from "../CardList/CardList";
import Headshot from "../Headshot/Headshot";
import Modal from "../Modal/Modal";
import { cardContents } from './cardContents';

const HomePage = () => {
  const [modalContent, setModalContent] = useState({});
  const setModal = (title, body) => setModalContent({ title, body });

  const [open, setOpen] = useState(false);
  const openModalAndSetContent = (modalContent) => {
    setOpen(true);
    setModal(modalContent.title, modalContent.body);
  };
  const closeModal = () => setOpen(false);

  return (
    <div className="content">
      <Modal open={open} close={closeModal}>
        {modalContent}
      </Modal>
      <div className="container">
        <div className="row">
          <div className="col-6">
            <div className="sticky-column">
              <p id="one">Hi, I'm</p>
              <div className="title">Steven Gu</div>
              <Headshot src="/linkedin.jpg" alt="Steven Gu" size="150px" />
              <div className="body">
                <hr></hr>
                <p>
                  I'm a fourth-year student studying Computer Science and Biology
                  at Northwestern University. I'm also an avid home cook,
                  violinist, gamer, and TTRPG enthusiast.
                </p>
              </div>
              <div className="row sticky-footer">
                <div className="col-6 icons">
                  <IconButton
                    icon="bi bi-github"
                    href="https://github.com/theogguu"
                  />
                  <IconButton
                    icon="bi bi-linkedin"
                    href="https://www.linkedin.com/in/steven-gu/"
                  />
                  <IconButton
                    icon="bi bi-instagram "
                    href="https://www.instagram.com/theogguu/"
                  />
                  <IconButton
                    icon="bi bi-envelope "
                    href="mailto:stevengu2024@u.northwestern.edu"
                  />
                </div>
                <div className="col resume">
                  <a href="/steven_gu_resume_fa23.pdf" target="_blank"><i>view my resume!</i></a>
                </div>
              </div>
            </div>
          </div>
          <div className="col">
            <CardList cards={cardContents} openModalAndSetContent={openModalAndSetContent} />
            <div className="footer">
              <hr></hr>
              Built with React and Node.js and deployed with Firebase. Favicon
              generated by
              <a href="https://favicon.io/"> favicon.io</a>. Website design
              inspired by{" "}
              <a href="https://brittanychiang.com/"> Brittany Chang</a>.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HomePage;
