// HomePage.js
import React, { useState } from 'react';
import "./HomePage.css";
import IconButton from "../IconButton/IconButton";
import CardList from "../CardList/CardList";
import Headshot from "../Headshot/Headshot";
import Modal from "../Modal/Modal";
import { cardContents } from './cardContents';

const HomePage = () => {
  const [modalContent, setModalContent] = useState({});
  const setModal = (title, body) => setModalContent({ title, body });

  const [open, setOpen] = useState(false);
  const openModalAndSetContent = (modalContent) => {
    setOpen(true);
    setModal(modalContent.title, modalContent.body);
  };
  const closeModal = () => setOpen(false);

  return (
    <div className="content">
      <Modal open={open} close={closeModal}>
        {modalContent}
      </Modal>
      <div className="d-lg-none container">

      <p id="one">Hi, I'm</p>
        <div className="title">Steven Gu</div>
        <Headshot src="/linkedin.jpg" alt="Steven Gu" size="12rem" />
        <div className="body">
          <hr></hr>
          <p>
            I'm a fourth-year student studying Computer Science and Biology
            at Northwestern University. I'm also an avid home cook,
            violinist, gamer, and TTRPG enthusiast.
          </p>
        </div>
        <div className="profile-footer">
          <div className="icons">
          <IconButton
                    icon="bi bi-github"
                    href="https://github.com/theogguu"
                    alt="Link to Steven's GitHub page"
                  />
                  <IconButton
                    icon="bi bi-linkedin"
                    href="https://www.linkedin.com/in/steven-gu/"
                    alt="Linked to Steven's LinkedIn page"
                  />
                  <IconButton
                    icon="bi bi-instagram"
                    href="https://www.instagram.com/theogguu/"
                    alt="Link to Steven's Instagram"
                  />
                  <IconButton
                    icon="bi bi-envelope"
                    href="mailto:stevengu2024@u.northwestern.edu"
                    alt="Send Email to stevengu2024@u.northwestern.edu"
                  />
          </div>
          <div className="resume">
            <a href="/steven_gu_resume_fa23.pdf" target="_blank"><i><b>view my resume!</b></i></a>
          </div>
        </div>
        <CardList cards={cardContents} openModalAndSetContent={openModalAndSetContent} />
        <div className="footer">
              <hr></hr>
              Built with <a href="https://react.dev/"> React</a> and 
              <a href="https://nodejs.org/"> Node.js</a> and deployed 
              with <a href="https://firebase.google.com/">Firebase</a>. 
              Favicon generated by
              <a href="https://favicon.io/"> favicon.io</a>. Color palette
              designed by <a href="https://www.radix-ui.com/colors"> Radix</a>.
               Website design
              inspired by{" "}
              <a href="https://brittanychiang.com/"> Brittany Chang</a>.
            </div>


      </div>

      <div className="d-none d-lg-block container">
        <div className="row">
          <div className="col-6">
            <div className="sticky-column">
              <p id="one">Hi! I'm</p>
              <div className="title">Steven Gu</div>
              <Headshot src="/linkedin.jpg" alt="Steven Gu" size="12rem" />
              <div className="body">
                <hr></hr>
                <p>
                  I'm a fourth-year student studying Computer Science and Biology
                  at Northwestern University. I'm also an avid home cook,
                  violinist, gamer, and TTRPG enthusiast.
                </p>
              </div>
              <div className="profile-footer">
                <div className="icons">
                  <IconButton
                    icon="bi bi-github"
                    href="https://github.com/theogguu"
                    aria-label="Link to Steven's GitHub page"
                    alt="GitHub"
                    
                  />
                  <IconButton
                    icon="bi bi-linkedin"
                    href="https://www.linkedin.com/in/steven-gu/"
                    alt="LinkedIn"
                    aria-label="Link to Steven's LinkedIn page"
                  />
                  <IconButton
                    icon="bi bi-instagram"
                    href="https://www.instagram.com/theogguu/"
                    alt="@theogguu"
                    aria-label="Link to Steven's Instagram page"
                  />
                  <IconButton
                    icon="bi bi-envelope"
                    href="mailto:stevengu2024@u.northwestern.edu"
                    alt="stevengu2024@u.northwestern.edu"
                    aria-label="Email Steven Gu"
                  />
                </div>
                <div className="resume">
                  <a href="/steven_gu_resume_fa23.pdf" target="_blank" alt="link to Steven's Resume" aria-label="View Steven's Resume"><i>view my resume!</i></a>
                </div>
              </div>
            </div>
          </div>
          <div className="col">
            <CardList cards={cardContents} openModalAndSetContent={openModalAndSetContent} />
            <div className="footer">
              <hr></hr>
              Built with <a href="https://react.dev/" aria-label="React"> React</a> and 
              <a href="https://nodejs.org/" aria-label="Node.js"> Node.js</a> and deployed 
              with <a href="https://firebase.google.com/" aria-label="Firebase">Firebase</a>. 
              Favicon generated by
              <a href="https://favicon.io/" aria-label="Favicon Generator"> favicon.io</a>. Color palette
              designed by <a href="https://www.radix-ui.com/colors" aria-label="Radix Color Palette"> Radix</a>.
              Website design
              inspired by{" "}
              <a href="https://brittanychiang.com/" aria-label="Brittany Chang's Website"> Brittany Chang</a>.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HomePage;
